name: pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: restore
        run: dotnet restore
      - name: set-vars
        id: set-vars
        run: |
          VERSION=1.0.${{ github.run_number }}
          BUILD_NAME="my-dotnet-build-$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "build_name=$BUILD_NAME" >> $GITHUB_OUTPUT
      - name: Build with version
        id: build 
        run: |
          dotnet build --configuration Release --no-restore -o build_output -p:Version=${{steps.set-vars.outputs.version}}

      - name: Test
        run: dotnet test --no-build --verbosity d

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.set-vars.outputs.build_name}}
          path: build_output

  # push-to-oct:
  #   steps:




