name: pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: restore
        run: dotnet restore
      
      - name: Build with version
        run: |
          VERSION=1.0.${{ github.run_number }}
          dotnet build --configuration Release --no-restore -o build_output -p:Version=$VERSION

      - name: Test
        run: dotnet test --no-build --verbosity d

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-dotnet-build
          path: build_output



